import type { ReceiptData } from "./interfaz";

export const INIT_DATA: ReceiptData = {
  codigo: "",
  fecha: "",
  cliente: "",
  direccion: "",
  iva: "",
  cuiltDni: "",
  localidad: "",
  contrato: "",
  inicio: "",
  finalizacion: "",
  enConceptoDe: "",
  direccionInmueble: "",
  propietario: "",
  dniPropietario: "",
  mesCorrespondiente: "",
  alquiler: "",
  aumentoPorcentual: 0,
  aproximado: false,
  otrosConceptos: "",
  observaciones: "",
  utilities: { edenor: "", gas: "", agua: "", expensas: "", abl: "", cochera: "" },
  diferencia: "",
  hayDiferencia: false,
  tipoAjuste: "",
  numeroRecibo: "",
  totalRecibos: "",
  punitorios: "",
  hayPunitorios: false,
};